apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-app
spec:
  selector:
    matchLabels:
      app: currency-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: currency-app
    spec:
      containers:
        - image: vskubev/currency
          imagePullPolicy: Always
          name: currency
          env:
            - name: REDIS_API_URL
              value: "http://redis-cache"
          ports:
            - containerPort: 8080