apiVersion: v1
kind: Service
metadata:
  name: currency-app
  namespace: currency-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: currency-app