apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: currency-app
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-cache